export const SCORING_SETTINGS_KEYS = {
  ARRAY_POSITION_MATCH: 'arrayPositionMatch',
};

export const SCORE_SETTINGS_VALUES = {
  [SCORING_SETTINGS_KEYS.ARRAY_POSITION_MATCH]: {
    FORCE_SAME_POSITION: 'strict',
    MATCH_ANY_POSITION: 'flex',
  },
};
